/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    agentId: BytesLike;
    wallet: AddressLike;
    generation: BigNumberish;
    createdAt: BigNumberish;
    isActive: boolean;
    dnaHash: BytesLike;
    profitAllTime: BigNumberish;
    tradeCount: BigNumberish;
    lastActiveAt: BigNumberish;
  };

  export type AgentStructOutput = [
    agentId: string,
    wallet: string,
    generation: bigint,
    createdAt: bigint,
    isActive: boolean,
    dnaHash: string,
    profitAllTime: bigint,
    tradeCount: bigint,
    lastActiveAt: bigint
  ] & {
    agentId: string;
    wallet: string;
    generation: bigint;
    createdAt: bigint;
    isActive: boolean;
    dnaHash: string;
    profitAllTime: bigint;
    tradeCount: bigint;
    lastActiveAt: bigint;
  };

  export type AgentMetricsStruct = {
    winRate: BigNumberish;
    sharpeRatio: BigNumberish;
    maxDrawdown: BigNumberish;
    fitnessScore: BigNumberish;
  };

  export type AgentMetricsStructOutput = [
    winRate: bigint,
    sharpeRatio: bigint,
    maxDrawdown: bigint,
    fitnessScore: bigint
  ] & {
    winRate: bigint;
    sharpeRatio: bigint;
    maxDrawdown: bigint;
    fitnessScore: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeAgents"
      | "agentIds"
      | "agentMetrics"
      | "agents"
      | "currentGeneration"
      | "eliminateAgent"
      | "getActiveAgentCount"
      | "getAgent"
      | "getAgentByWallet"
      | "getAllAgentIds"
      | "owner"
      | "registerAgent"
      | "renounceOwnership"
      | "setAgentStatus"
      | "startNewGeneration"
      | "totalAgents"
      | "transferOwnership"
      | "updateAgentMetrics"
      | "walletToAgentId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentEliminated"
      | "AgentMetricsUpdated"
      | "AgentRegistered"
      | "AgentStatusChanged"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentMetrics",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "currentGeneration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eliminateAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAgentByWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgentIds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentStatus",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "startNewGeneration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentMetrics",
    values: [BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "walletToAgentId",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eliminateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startNewGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletToAgentId",
    data: BytesLike
  ): Result;
}

export namespace AgentEliminatedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    generation: BigNumberish,
    finalProfit: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    generation: bigint,
    finalProfit: bigint
  ];
  export interface OutputObject {
    agentId: string;
    generation: bigint;
    finalProfit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentMetricsUpdatedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    profitAllTime: BigNumberish,
    tradeCount: BigNumberish,
    fitnessScore: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    profitAllTime: bigint,
    tradeCount: bigint,
    fitnessScore: bigint
  ];
  export interface OutputObject {
    agentId: string;
    profitAllTime: bigint;
    tradeCount: bigint;
    fitnessScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    wallet: AddressLike,
    generation: BigNumberish,
    dnaHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    wallet: string,
    generation: bigint,
    dnaHash: string
  ];
  export interface OutputObject {
    agentId: string;
    wallet: string;
    generation: bigint;
    dnaHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [agentId: BytesLike, isActive: boolean];
  export type OutputTuple = [agentId: string, isActive: boolean];
  export interface OutputObject {
    agentId: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeAgents: TypedContractMethod<[], [bigint], "view">;

  agentIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentMetrics: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        winRate: bigint;
        sharpeRatio: bigint;
        maxDrawdown: bigint;
        fitnessScore: bigint;
      }
    ],
    "view"
  >;

  agents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        agentId: string;
        wallet: string;
        generation: bigint;
        createdAt: bigint;
        isActive: boolean;
        dnaHash: string;
        profitAllTime: bigint;
        tradeCount: bigint;
        lastActiveAt: bigint;
      }
    ],
    "view"
  >;

  currentGeneration: TypedContractMethod<[], [bigint], "view">;

  eliminateAgent: TypedContractMethod<
    [agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getActiveAgentCount: TypedContractMethod<[], [bigint], "view">;

  getAgent: TypedContractMethod<
    [agentId: BytesLike],
    [
      [
        AgentRegistry.AgentStructOutput,
        AgentRegistry.AgentMetricsStructOutput
      ] & {
        agent: AgentRegistry.AgentStructOutput;
        metrics: AgentRegistry.AgentMetricsStructOutput;
      }
    ],
    "view"
  >;

  getAgentByWallet: TypedContractMethod<
    [wallet: AddressLike],
    [string],
    "view"
  >;

  getAllAgentIds: TypedContractMethod<[], [string[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [agentId: BytesLike, wallet: AddressLike, dnaHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentStatus: TypedContractMethod<
    [agentId: BytesLike, isActive: boolean],
    [void],
    "nonpayable"
  >;

  startNewGeneration: TypedContractMethod<[], [void], "nonpayable">;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgentMetrics: TypedContractMethod<
    [agentId: BytesLike, profitDelta: BigNumberish, wasWinningTrade: boolean],
    [void],
    "nonpayable"
  >;

  walletToAgentId: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentMetrics"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        winRate: bigint;
        sharpeRatio: bigint;
        maxDrawdown: bigint;
        fitnessScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        agentId: string;
        wallet: string;
        generation: bigint;
        createdAt: bigint;
        isActive: boolean;
        dnaHash: string;
        profitAllTime: bigint;
        tradeCount: bigint;
        lastActiveAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentGeneration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "eliminateAgent"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [
      [
        AgentRegistry.AgentStructOutput,
        AgentRegistry.AgentMetricsStructOutput
      ] & {
        agent: AgentRegistry.AgentStructOutput;
        metrics: AgentRegistry.AgentMetricsStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByWallet"
  ): TypedContractMethod<[wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAllAgentIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentId: BytesLike, wallet: AddressLike, dnaHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentStatus"
  ): TypedContractMethod<
    [agentId: BytesLike, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startNewGeneration"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgentMetrics"
  ): TypedContractMethod<
    [agentId: BytesLike, profitDelta: BigNumberish, wasWinningTrade: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "walletToAgentId"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "AgentEliminated"
  ): TypedContractEvent<
    AgentEliminatedEvent.InputTuple,
    AgentEliminatedEvent.OutputTuple,
    AgentEliminatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentMetricsUpdated"
  ): TypedContractEvent<
    AgentMetricsUpdatedEvent.InputTuple,
    AgentMetricsUpdatedEvent.OutputTuple,
    AgentMetricsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentEliminated(bytes32,uint8,int256)": TypedContractEvent<
      AgentEliminatedEvent.InputTuple,
      AgentEliminatedEvent.OutputTuple,
      AgentEliminatedEvent.OutputObject
    >;
    AgentEliminated: TypedContractEvent<
      AgentEliminatedEvent.InputTuple,
      AgentEliminatedEvent.OutputTuple,
      AgentEliminatedEvent.OutputObject
    >;

    "AgentMetricsUpdated(bytes32,int256,uint256,uint256)": TypedContractEvent<
      AgentMetricsUpdatedEvent.InputTuple,
      AgentMetricsUpdatedEvent.OutputTuple,
      AgentMetricsUpdatedEvent.OutputObject
    >;
    AgentMetricsUpdated: TypedContractEvent<
      AgentMetricsUpdatedEvent.InputTuple,
      AgentMetricsUpdatedEvent.OutputTuple,
      AgentMetricsUpdatedEvent.OutputObject
    >;

    "AgentRegistered(bytes32,address,uint8,bytes32)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusChanged(bytes32,bool)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
