/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StakingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeAgents"
      | "agentPools"
      | "claimRewards"
      | "createAgentPool"
      | "deactivatePool"
      | "distributeProfits"
      | "getPoolStats"
      | "getStakeInfo"
      | "owner"
      | "protocolFeePercent"
      | "renounceOwnership"
      | "setProtocolFee"
      | "stake"
      | "stakes"
      | "stakingToken"
      | "totalValueLocked"
      | "transferOwnership"
      | "unstake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProfitDistributed"
      | "RewardsClaimed"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentPools",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgentPool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeProfits",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalValueLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgentPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeProfits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitDistributedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    profitAmount: BigNumberish,
    rewardPerShare: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    profitAmount: bigint,
    rewardPerShare: bigint
  ];
  export interface OutputObject {
    agentId: string;
    profitAmount: bigint;
    rewardPerShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    staker: AddressLike,
    agentId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [staker: string, agentId: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    agentId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    staker: AddressLike,
    agentId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [staker: string, agentId: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    agentId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    staker: AddressLike,
    agentId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [staker: string, agentId: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    agentId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingPool extends BaseContract {
  connect(runner?: ContractRunner | null): StakingPool;
  waitForDeployment(): Promise<this>;

  interface: StakingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeAgents: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentPools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        agentId: string;
        totalStaked: bigint;
        totalProfitGenerated: bigint;
        rewardPerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  claimRewards: TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;

  createAgentPool: TypedContractMethod<
    [agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  deactivatePool: TypedContractMethod<
    [agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  distributeProfits: TypedContractMethod<
    [agentId: BytesLike, profitAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPoolStats: TypedContractMethod<
    [agentId: BytesLike],
    [
      [bigint, bigint, bigint, boolean] & {
        totalStaked: bigint;
        totalProfit: bigint;
        rewardPerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getStakeInfo: TypedContractMethod<
    [agentId: BytesLike, staker: AddressLike],
    [
      [bigint, bigint, bigint] & {
        stakedAmount: bigint;
        pendingRewards: bigint;
        stakedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolFeePercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setProtocolFee: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        stakedAt: bigint;
        lastClaimAt: bigint;
        rewardsAccrued: bigint;
      }
    ],
    "view"
  >;

  stakingToken: TypedContractMethod<[], [string], "view">;

  totalValueLocked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeAgents"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentPools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        agentId: string;
        totalStaked: bigint;
        totalProfitGenerated: bigint;
        rewardPerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAgentPool"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivatePool"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeProfits"
  ): TypedContractMethod<
    [agentId: BytesLike, profitAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPoolStats"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [
      [bigint, bigint, bigint, boolean] & {
        totalStaked: bigint;
        totalProfit: bigint;
        rewardPerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [agentId: BytesLike, staker: AddressLike],
    [
      [bigint, bigint, bigint] & {
        stakedAmount: bigint;
        pendingRewards: bigint;
        stakedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFee"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        stakedAt: bigint;
        lastClaimAt: bigint;
        rewardsAccrued: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalValueLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProfitDistributed"
  ): TypedContractEvent<
    ProfitDistributedEvent.InputTuple,
    ProfitDistributedEvent.OutputTuple,
    ProfitDistributedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProfitDistributed(bytes32,int256,uint256)": TypedContractEvent<
      ProfitDistributedEvent.InputTuple,
      ProfitDistributedEvent.OutputTuple,
      ProfitDistributedEvent.OutputObject
    >;
    ProfitDistributed: TypedContractEvent<
      ProfitDistributedEvent.InputTuple,
      ProfitDistributedEvent.OutputTuple,
      ProfitDistributedEvent.OutputObject
    >;

    "RewardsClaimed(address,bytes32,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "Staked(address,bytes32,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,bytes32,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
