/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentRegistry,
  IAgentRegistryInterface,
} from "../../../contracts/ExecutionRouter.sol/IAgentRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "agents",
    outputs: [
      {
        internalType: "bytes32",
        name: "agentId_",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "generation",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "createdAt",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isActive",
        type: "bool",
      },
      {
        internalType: "bytes32",
        name: "dnaHash",
        type: "bytes32",
      },
      {
        internalType: "int256",
        name: "profitAllTime",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "tradeCount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastActiveAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "int256",
        name: "profitDelta",
        type: "int256",
      },
      {
        internalType: "bool",
        name: "wasWinningTrade",
        type: "bool",
      },
    ],
    name: "updateAgentMetrics",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentRegistryInterface {
    return new Interface(_abi) as IAgentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentRegistry {
    return new Contract(address, _abi, runner) as unknown as IAgentRegistry;
  }
}
