/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ExecutionRouter {
  export type TradeStruct = {
    agentId: BytesLike;
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    amountOut: BigNumberish;
    timestamp: BigNumberish;
    txHash: BytesLike;
    pnl: BigNumberish;
    gasUsed: BigNumberish;
  };

  export type TradeStructOutput = [
    agentId: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    timestamp: bigint,
    txHash: string,
    pnl: bigint,
    gasUsed: bigint
  ] & {
    agentId: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    timestamp: bigint;
    txHash: string;
    pnl: bigint;
    gasUsed: bigint;
  };
}

export interface ExecutionRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "agentTrades"
      | "allTrades"
      | "depositForAgent"
      | "emergencyWithdraw"
      | "executeTrade"
      | "getAgentBalance"
      | "getAgentTradeCount"
      | "getAgentTrades"
      | "owner"
      | "renounceOwnership"
      | "setAgentRegistry"
      | "totalSystemPnL"
      | "totalTradesExecuted"
      | "transferOwnership"
      | "withdrawForAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsDeposited"
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "TradeExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentTrades",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allTrades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForAgent",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTrade",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentBalance",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentTradeCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentTrades",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSystemPnL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTradesExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawForAgent",
    values: [BytesLike, AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allTrades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositForAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentTradeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSystemPnL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTradesExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawForAgent",
    data: BytesLike
  ): Result;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: string, token: string, amount: bigint];
  export interface OutputObject {
    agentId: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    agentId: BytesLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: string, token: string, amount: bigint];
  export interface OutputObject {
    agentId: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeExecutedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    pnl: BigNumberish,
    txHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    pnl: bigint,
    txHash: string
  ];
  export interface OutputObject {
    agentId: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    pnl: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExecutionRouter extends BaseContract {
  connect(runner?: ContractRunner | null): ExecutionRouter;
  waitForDeployment(): Promise<this>;

  interface: ExecutionRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  agentTrades: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        agentId: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        amountOut: bigint;
        timestamp: bigint;
        txHash: string;
        pnl: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;

  allTrades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        agentId: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        amountOut: bigint;
        timestamp: bigint;
        txHash: string;
        pnl: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;

  depositForAgent: TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeTrade: TypedContractMethod<
    [
      agentId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      txHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getAgentBalance: TypedContractMethod<
    [agentId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getAgentTradeCount: TypedContractMethod<
    [agentId: BytesLike],
    [bigint],
    "view"
  >;

  getAgentTrades: TypedContractMethod<
    [agentId: BytesLike],
    [ExecutionRouter.TradeStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentRegistry: TypedContractMethod<
    [_agentRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  totalSystemPnL: TypedContractMethod<[], [bigint], "view">;

  totalTradesExecuted: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawForAgent: TypedContractMethod<
    [
      agentId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentTrades"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        agentId: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        amountOut: bigint;
        timestamp: bigint;
        txHash: string;
        pnl: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "allTrades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        agentId: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        amountOut: bigint;
        timestamp: bigint;
        txHash: string;
        pnl: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositForAgent"
  ): TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTrade"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      txHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentBalance"
  ): TypedContractMethod<
    [agentId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentTradeCount"
  ): TypedContractMethod<[agentId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentTrades"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [ExecutionRouter.TradeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[_agentRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalSystemPnL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTradesExecuted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawForAgent"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TradeExecuted"
  ): TypedContractEvent<
    TradeExecutedEvent.InputTuple,
    TradeExecutedEvent.OutputTuple,
    TradeExecutedEvent.OutputObject
  >;

  filters: {
    "FundsDeposited(bytes32,address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsWithdrawn(bytes32,address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TradeExecuted(bytes32,address,address,uint256,uint256,int256,bytes32)": TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
    TradeExecuted: TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
  };
}
