/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "agents" | "updateAgentMetrics"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "agents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "updateAgentMetrics",
    values: [BytesLike, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentMetrics",
    data: BytesLike
  ): Result;
}

export interface IAgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [agentId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        agentId_: string;
        wallet: string;
        generation: bigint;
        createdAt: bigint;
        isActive: boolean;
        dnaHash: string;
        profitAllTime: bigint;
        tradeCount: bigint;
        lastActiveAt: bigint;
      }
    ],
    "view"
  >;

  updateAgentMetrics: TypedContractMethod<
    [agentId: BytesLike, profitDelta: BigNumberish, wasWinningTrade: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        agentId_: string;
        wallet: string;
        generation: bigint;
        createdAt: bigint;
        isActive: boolean;
        dnaHash: string;
        profitAllTime: bigint;
        tradeCount: bigint;
        lastActiveAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateAgentMetrics"
  ): TypedContractMethod<
    [agentId: BytesLike, profitDelta: BigNumberish, wasWinningTrade: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
